
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class StudentDashBoard extends javax.swing.JFrame {
    static int prn1;
    static String name1;
    /**
     * Creates new form StudentDashBoard
     */
    public StudentDashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBackground = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btBookIssue = new javax.swing.JButton();
        btCheckDues = new javax.swing.JButton();
        btDisplayBooks = new javax.swing.JButton();
        btBacktoLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pBackground.setBackground(new java.awt.Color(0, 153, 153));

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/491-4910202_law-faculty-symbiosis-international-university-pune-symbiosis.png"))); // NOI18N

        btBookIssue.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 16)); // NOI18N
        btBookIssue.setText("Book Issue");
        btBookIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBookIssueActionPerformed(evt);
            }
        });

        btCheckDues.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 16)); // NOI18N
        btCheckDues.setText("Check Pending Dues");
        btCheckDues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCheckDuesActionPerformed(evt);
            }
        });

        btDisplayBooks.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 16)); // NOI18N
        btDisplayBooks.setText("Display the Books");
        btDisplayBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDisplayBooksActionPerformed(evt);
            }
        });

        btBacktoLogin.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 10)); // NOI18N
        btBacktoLogin.setText("Back to Login Page");
        btBacktoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBacktoLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btBookIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDisplayBooks)
                    .addComponent(btCheckDues))
                .addGap(101, 101, 101)
                .addComponent(btBacktoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btBookIssue, btCheckDues, btDisplayBooks});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btDisplayBooks)
                .addGap(18, 18, 18)
                .addComponent(btBookIssue)
                .addGap(18, 18, 18)
                .addComponent(btCheckDues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btBacktoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btBookIssue, btCheckDues, btDisplayBooks});

        javax.swing.GroupLayout pBackgroundLayout = new javax.swing.GroupLayout(pBackground);
        pBackground.setLayout(pBackgroundLayout);
        pBackgroundLayout.setHorizontalGroup(
            pBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pBackgroundLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pBackgroundLayout.setVerticalGroup(
            pBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBackgroundLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lbLogo)
                .addGap(72, 72, 72)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBacktoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBacktoLoginActionPerformed
        this.dispose();
        LoginDashboard ld=new LoginDashboard();
        ld.setVisible(true);
    }//GEN-LAST:event_btBacktoLoginActionPerformed

    private void btDisplayBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDisplayBooksActionPerformed
        this.dispose();
        BookTable bt=new BookTable();
        bt.g(true);
        bt.setVisible(true);
    }//GEN-LAST:event_btDisplayBooksActionPerformed

    private void btBookIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBookIssueActionPerformed
        StudentBorrowBook bb = new StudentBorrowBook();
        this.dispose();
        bb.main(prn1,name1);
    }//GEN-LAST:event_btBookIssueActionPerformed

    private void btCheckDuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCheckDuesActionPerformed
        try{                                            
            Connection con=StudentLogin.connect();
            Statement statement=con.createStatement();
            ResultSet resultSet2;
            int fine = 0;
            resultSet2 = statement.executeQuery(
                    "select fine from students where prn="+prn1);
            while (resultSet2.next()) {
                fine = resultSet2.getInt("fine");
            }
            JOptionPane.showMessageDialog(jPanel2,"Fine:"+fine);
            
        }catch (SQLException ex) {
            Logger.getLogger(StudentDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btCheckDuesActionPerformed

    /**
     * @param prn
     * @param name
     */
    public static void main(int prn,String name) {
        prn1=prn;
        name1=name;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBacktoLogin;
    private javax.swing.JButton btBookIssue;
    private javax.swing.JButton btCheckDues;
    private javax.swing.JButton btDisplayBooks;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JPanel pBackground;
    // End of variables declaration//GEN-END:variables
}
